export const MOCK_EVENTS = [
  {
    id: 1,
    title: "Neon Dreams Music Festival",
    date: "April 15, 2026",
    time: "06:00 PM",
    location: "Skyline Arena, Mumbai",
    price: 1500,
    category: "Concerts",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1200",
    description: "Experience a night of electrifying music and stunning visuals at the Neon Dreams Music Festival. Featuring top international DJs and underground artists.",
    organizer: "Infinity Events",
    isSponsored: true,
  },
  {
    id: 2,
    title: "Tech Innovators Summit 2026",
    date: "May 22, 2026",
    time: "09:00 AM",
    location: "Global Convention Center, Bangalore",
    price: 2500,
    category: "Workshops",
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=1200",
    description: "Join the brightest minds in technology for a day of inspiring keynotes, hands-on workshops, and unparalleled networking opportunities.",
    organizer: "InnovateX",
  },
  {
    id: 3,
    title: "Eco-Friendly Living Seminar",
    date: "June 05, 2026",
    time: "10:30 AM",
    location: "Green Gardens Hub, Pune",
    price: 0.00,
    category: "Seminars",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=1200",
    description: "Discover practical tips and sustainable practices to lead a more eco-friendly lifestyle. Learn from experts in urban gardening, zero-waste living, and more.",
    organizer: "Green Earth Org",
  },
  {
    id: 4,
    title: "Summer Vibes Beach Party",
    date: "July 12, 2026",
    time: "02:00 PM",
    location: "Ocean Blue Coast, Goa",
    price: 800,
    category: "Concerts",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80&w=1200",
    description: "Kick off the summer at our exclusive beach party! Enjoy live bands, beach volleyball, fire shows, and a selection of exotic cocktails as the sun sets.",
    organizer: "Oceanic Vibes",
  },
  {
    id: 5,
    title: "Modern Wedding Expo",
    date: "August 20, 2026",
    time: "11:00 AM",
    location: "Grand Ballroom, Jaipur",
    price: 500,
    category: "Weddings",
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=1200",
    description: "The ultimate wedding planning experience. Meet vendors, see bridal fashion, and find everything you need for your perfect day.",
    organizer: "Wedding Bliss",
  },
  {
    id: 6,
    title: "Global AI Summit",
    date: "September 15, 2026",
    time: "09:30 AM",
    location: "Silicon Convention Plaza, Hyderabad",
    price: 3500,
    category: "Corporate",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=1200",
    description: "The biggest gathering of AI talent in the world. Explore the future of Generative AI, robotics, and automation.",
    organizer: "TechWorld",
    isSponsored: true,
  },
  {
    id: 7,
    title: "Classical Music Night",
    date: "October 05, 2026",
    time: "07:00 PM",
    location: "City Heritage Hall, Delhi",
    price: 1200,
    category: "Concerts",
    image: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&q=80&w=1200",
    description: "A soulful evening of Indian classical music featuring world-renowned instrumentalists and vocalists.",
    organizer: "Heritage Souls",
  },
  {
    id: 8,
    title: "Startup Founders Meetup",
    date: "November 10, 2026",
    time: "05:00 PM",
    location: "Venture Park, Bangalore",
    price: 300,
    category: "Corporate",
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&q=80&w=1200",
    description: "Connect with fellow founders, share experiences, and find potential collaborators for your next big thing.",
    organizer: "Founders Circle",
  },
  {
    id: 9,
    title: "Yoga & Wellness Retreat",
    date: "December 01, 2026",
    time: "06:00 AM",
    location: "Zen Wellness Center, Rishikesh",
    price: 5000,
    category: "Workshops",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=1200",
    description: "A three-day immersive retreat focused on holistic wellness, meditation, and advanced yoga practices.",
    organizer: "Peace Seekers",
  },
  {
    id: 10,
    title: "Gourmet Food Festival",
    date: "January 20, 2027",
    time: "12:00 PM",
    location: "Foodie Square, Kolkata",
    price: 250,
    category: "Workshops",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=1200",
    description: "Taste the best cuisines from around the city. Live cooking demos from celebrity chefs and food stalls from top restaurants.",
    organizer: "Kolkata Foodies",
  },
  {
    id: 11,
    title: "Photography Masterclass",
    date: "February 15, 2027",
    time: "10:00 AM",
    location: "Visual Arts Studio, Chennai",
    price: 1800,
    category: "Workshops",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=1200",
    description: "Learn the art of portrait and landscape photography from industry veterans. Practical sessions included.",
    organizer: "Lens Masters",
  },
  {
    id: 12,
    title: "Stock Market Strategy 2027",
    date: "March 10, 2027",
    time: "04:30 PM",
    location: "Finance Hub, Ahmedabad",
    price: 900,
    category: "Seminars",
    image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&q=80&w=1200",
    description: "Navigate the complex world of stock markets with expert-led strategies for the upcoming fiscal year.",
    organizer: "Wealth Wise",
  }
];

